version: '3.8'

services:
  mongo:
    image: mongo
    container_name: spring-mongo
    restart: always
    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
volumes:
  db-data: { }
